name: Plan DCM objects to test

on:
  pull_request:
    branches: [test]
    paths:
      - "sources/definitions/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: test
    env:
      SNOWFLAKE_USER: ${{ vars.TEST_DEPLOY_SNOWFLAKE_USER }}
    steps:
      - uses: actions/checkout@v7

      - uses: snowflakedb/snowflake-actions/dcm/plan@v3
        with:
          target: TEST
          project-path: ./
          snowflake-user: ${{ env.SNOWFLAKE_USER }}
          comment-on-pr: "true"